services:
  backend:
    build: backend
    image: node_backend
    container_name: node_backend
    restart: always

    ports:
      - "3000:3000"  # Node.js backend
    networks:
      - app_network
    depends_on:
      mariadb:
        condition: service_healthy
    # volumes:
    #   - ./backend:/app
    env_file:
      - .env

  mariadb:
    image: mariadb
    build: ./mariadb
    container_name: mariadb
    restart: always
    networks:
      - app_network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10
      timeout: 5s

networks:
  app_network:
    driver: bridge
